-- Sprint 5 : Seeds événements Elonga
-- 5 événements de démonstration

INSERT INTO elonga_events (
  title, description, pillar,
  location_name, location_address,
  latitude, longitude, city,
  starts_at, ends_at,
  max_participants, zora_reward, status
) VALUES
('Marche sportive matinale',
 'Marche en groupe de 5km le long de la côte.',
 'activite', 'Côte Sauvage',
 'Côte Sauvage, Pointe-Noire',
 -4.7960, 11.8270, 'pointe_noire',
 NOW() + INTERVAL '2 days 8 hours',
 NOW() + INTERVAL '2 days 10 hours',
 40, 50, 'published'),
('Atelier cuisine équilibrée',
 'Cuisiner sain avec des ingrédients locaux.',
 'nutrition', 'Centre communautaire Tchikobo',
 'Tchikobo, Pointe-Noire',
 -4.8090, 11.8500, 'pointe_noire',
 NOW() + INTERVAL '3 days 15 hours',
 NOW() + INTERVAL '3 days 18 hours',
 25, 40, 'published'),
('Dépistage tension & glycémie',
 'Bilan santé gratuit : tension, glycémie.',
 'anti_infectieux', 'Place de la Mairie',
 'Place de la Mairie, Brazzaville',
 -4.2667, 15.2840, 'brazzaville',
 NOW() + INTERVAL '5 days 9 hours',
 NOW() + INTERVAL '5 days 13 hours',
 60, 30, 'published'),
('Session basket communautaire',
 'Match amical basket, équipes mixtes.',
 'activite', 'Terrain de basket Bacongo',
 'Bacongo, Brazzaville',
 -4.2900, 15.2750, 'brazzaville',
 NOW() + INTERVAL '7 days 16 hours',
 NOW() + INTERVAL '7 days 18 hours',
 30, 50, 'published'),
('Atelier bien-être & respiration',
 'Respiration, gestion du stress, méditation.',
 'activite', 'Jardin de la Préfecture',
 'Centre-ville, Brazzaville',
 -4.2694, 15.2700, 'brazzaville',
 NOW() + INTERVAL '10 days 7 hours',
 NOW() + INTERVAL '10 days 9 hours',
 20, 40, 'published');
