name: Bolamu — Dev
values:
  - key: base_url
    value: 'https://bolamu-backend.onrender.com/api/v1'
    enabled: true
  - key: admin_phone
    value: '+242060000099'
    enabled: true
  - key: admin_password
    value: 'Bolamu2026!'
    enabled: true
  - key: admin_token
    value: ''
    enabled: true
  - key: patient_phone
    value: ''
    enabled: true
  - key: patient_password
    value: ''
    enabled: true
  - key: patient_token
    value: ''
    enabled: true
  - key: doctor_phone
    value: ''
    enabled: true
  - key: upload_token
    value: ''
    enabled: true
  - key: file_id
    value: ''
    enabled: true
  - key: file_id_diploma
    value: ''
    enabled: true
  - key: file_id_ordre
    value: ''
    enabled: true
